export const COMPONENTS = {
    footswitch: {
        name: 'Footswitch (3PDT)',
        holeShape: 'circle',
        holeDiameter: 12.2,  // 12mm + 0.2 tolerance
        validFaces: ['top'],
        color: 0xe94560,
        reinforced: true,
        reinforceOuter: 28,
        reinforceThick: 2,
        ribCount: 4,
    },
    led5mm: {
        name: 'LED (5mm)',
        holeShape: 'circle',
        holeDiameter: 5.7,
        validFaces: ['top'],
        color: 0x00ff88,
    },
    led3mm: {
        name: 'LED (3mm)',
        holeShape: 'circle',
        holeDiameter: 3.7,
        validFaces: ['top'],
        color: 0x00cc66,
    },
    toggle: {
        name: 'Toggle Switch',
        holeShape: 'circle',
        holeDiameter: 6.7,
        validFaces: ['top'],
        color: 0xffaa00,
    },
    guitarJack: {
        name: '1/4" Guitar Jack',
        holeShape: 'circle',
        holeDiameter: 9.7,
        validFaces: ['front', 'back', 'left', 'right'],
        color: 0xcc66ff,
    },
    dcJack: {
        name: 'DC Jack (2.1mm)',
        holeShape: 'circle',
        holeDiameter: 8.2,
        validFaces: ['front', 'back', 'left', 'right'],
        color: 0xff6644,
    },
    usbC: {
        name: 'USB-C Jack',
        holeShape: 'roundrect',
        holeWidth: 9.7,
        holeHeight: 3.7,
        holeRadius: 1.5,
        validFaces: ['front', 'back', 'left', 'right'],
        color: 0x44aaff,
    },
    pot: {
        name: 'Potentiometer',
        holeShape: 'circle',
        holeDiameter: 7.2,
        validFaces: ['top'],
        color: 0xaaaa00,
    },
    screwM3: {
        name: 'M3 Screw Hole',
        holeShape: 'circle',
        holeDiameter: 3.4,
        validFaces: ['top', 'front', 'back', 'left', 'right'],
        color: 0x888888,
    },
    screwM25: {
        name: 'M2.5 Screw Hole',
        holeShape: 'circle',
        holeDiameter: 2.9,
        validFaces: ['top', 'front', 'back', 'left', 'right'],
        color: 0x777777,
    },
};
